CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(250),
    email VARCHAR (254),
    CONSTRAINT pk_users PRIMARY KEY(id),
    CONSTRAINT uq_users_name UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50),
    CONSTRAINT pk_categories PRIMARY KEY(id),
    CONSTRAINT uq_category_name UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(120),
    description VARCHAR(7000),
    annotation VARCHAR(2000),
    event_date TIMESTAMP WITHOUT TIME ZONE,
    created_on TIMESTAMP WITHOUT TIME ZONE,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    paid BOOLEAN,
    request_moderation BOOLEAN,
    event_status VARCHAR(100),
    participation_limit INTEGER,
    location_id BIGINT,
    category_id BIGINT,
    user_id BIGINT,
    CONSTRAINT pk_events PRIMARY KEY(id),
    CONSTRAINT fk_event_to_location FOREIGN KEY(location_id),
    CONSTRAINT fk_events_to_categories FOREIGN KEY(category_id),
    CONSTRAINT fk_events_to_users FOREIGN KEY(user_id)
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    CONSTRAINT pk_locations PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
    request_status VARCHAR(50),
    event_id BIGINT,
    user_id BIGINT,
    CONSTRAINT pk_requests PRIMARY KEY(id),
    CONSTRAINT fk_request_to_event FOREIGN KEY(event_id),
    CONSTRAINT fk_request_to_user FOREIGN KEY (user_id)
);